version: "2"

services:
  mongodb:
    image: mongo
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: booksy
  api:
    build: "./server"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
